"""
Cyberforecaster ML Models
==========================

Inference modules for the two ML models:

1. flow_classifier_infer.py — Fast per-flow attack classifier (XGBoost)
   - predict_flow(flow_dict) -> (label, confidence)
   - predict_flow_proba(flow_dict) -> {label: probability}

2. stage_forecaster_infer.py — GRU sequence model for attack stage forecasting
   - forecast_host(host_ip, recent_flows) -> {stage_probs, risk_score, projected_risk_curve}

Model artifacts (.joblib, .pth) are generated by running the training scripts:
    python training/train_flow_classifier.py <labeled_csvs>
    python training/train_stage_forecaster.py <labeled_csvs>
"""
